/** 机器人固定通知的文案和格式化参数；动态内容只参与显式插值。 */
export interface AtmosphereNotices {
  readonly statusContextUsage: (percent: string) => string;
  readonly blockAlreadyRecorded: (warning: string) => string;
  readonly blockKicked: (count: number) => string;
  readonly unblockNotRecorded: (label: string) => string;
  readonly batchKickAborted: string;
  readonly gagChannelEntry: string;
  readonly adDetected: (label: string, reason: string) => string;
  readonly adNoManagedChat: (head: string) => string;
  readonly adPartialBan: (head: string, enforcedChats: number, failedChats: number) => string;
  readonly adBanned: (head: string) => string;
  readonly proxyFailed: (targetChatId: number) => string;
  readonly adConfigInvalid: (file: string) => string;
  readonly aiConfigInvalid: (file: string) => string;
  readonly batchKickRejected: string;
  readonly batchKickSupergroupOnly: string;
  readonly joinLogUnavailable: string;
  readonly batchKickEmpty: (duration: string) => string;
  readonly batchKickResult: (values: Readonly<{ duration: string; recordCount: number; scanned: number; kicked: number; absent: number; protected: number; blocked: number; forbidden: number; failed: number; abortedNotice: string }>) => string;
  readonly blockRejected: (actorLabel: string) => string;
  readonly blockCurrentChat: string;
  readonly blockProtected: (targetLabel: string) => string;
  readonly blockPersistFailed: string;
  readonly blockNoManagedChat: (targetLabel: string, persistWarning: string) => string;
  readonly blockAllFailed: (targetLabel: string, persistWarning: string) => string;
  readonly blockNotAdminHere: string;
  readonly blockPartialFailure: (failedCount: number) => string;
  readonly blockRecorded: (persistWarning: string) => string;
  readonly blockResult: (values: Readonly<{ notAdminHereNote: string; targetLabel: string; actionNote: string; failedNote: string; blocklistNote: string }>) => string;
  readonly statusTitle: string;
  readonly statusProcess: string;
  readonly statusModels: string;
  readonly statusGag: (activeGagSessions: number, capacity: number) => string;
  readonly statusTranslate: (activeTranslateSessions: number, capacity: number) => string;
  readonly statusPermissions: string;
  readonly statusPermissionsUnknown: string;
  readonly statusFeatures: string;
  readonly statusRejected: (actorLabel: string) => string;
  readonly actionUsage: string;
  readonly actionMissingTarget: (actionWord: string, command: string) => string;
  readonly actionInvalidTarget: (rawArgument: string, actionWord: string) => string;
  readonly actionUnknownTarget: (rawUsername: string, actionWord: string) => string;
  readonly actionConflictingTarget: (rawArgument: string, actionWord: string) => string;
  readonly actionSelfTarget: (actionWord: string) => string;
  readonly clearContextRejected: (actorLabel: string) => string;
  readonly clearContextFailed: string;
  readonly clearContextDone: string;
  readonly copyAlreadyRunning: (targetLabel: string) => string;
  readonly copyOtherTarget: string;
  readonly copyStarting: (targetLabel: string, modeDescription: string) => string;
  readonly copyAvatarChanged: (targetLabel: string) => string;
  readonly copyAvatarFailed: (targetLabel: string) => string;
  readonly copyNotRunning: string;
  readonly copyStopped: string;
  readonly copyAvatarRestored: string;
  readonly copyAvatarRestoreFailed: string;
  readonly copyCooldown: (remaining: string) => string;
  readonly unknownActor: string;
  readonly gagRejected: (actorLabel: string, command: string) => string;
  readonly gagGroupOnly: string;
  readonly gagNotInitialized: string;
  readonly gagMissingRights: string;
  readonly gagToolTooLong: string;
  readonly gagCapacity: (capacity: number) => string;
  readonly gagEnding: (targetLabel: string) => string;
  readonly gagExists: (targetLabel: string) => string;
  readonly gagTargetAbsent: (targetLabel: string) => string;
  readonly gagMembershipUnknown: (targetLabel: string) => string;
  readonly ungagEnding: (targetLabel: string) => string;
  readonly ungagStarting: (targetLabel: string) => string;
  readonly ungagAbsent: (targetLabel: string) => string;
  readonly gagPublicNotice: (values: Readonly<{ targetLabel: string; tool: string; durationMinutes: number; channelEntry: string }>) => string;
  readonly gagSpeakNotice: (targetLabel: string) => string;
  readonly gagExpired: string;
  readonly gagRemoved: string;
  readonly gagEndedNotice: (reasonText: string, targetLabel: string, tool: string) => string;
  readonly iconRestoring: string;
  readonly iconRestored: string;
  readonly iconRestoreFailed: string;
  readonly iconStarting: (targetLabel: string) => string;
  readonly iconChanged: (targetLabel: string) => string;
  readonly iconFailed: (targetLabel: string) => string;
  readonly inlineRateLimitTitle: string;
  readonly inlineRateLimitDescription: (windowSeconds: number, maxCalls: number) => string;
  readonly inlineRateLimitBody: (windowSeconds: number, maxCalls: number) => string;
  readonly moodQueryConfigInvalid: (file: string) => string;
  readonly moodQueryDisabled: string;
  readonly moodQueryFailed: string;
  readonly moodCurrent: (moodName: string) => string;
  readonly moodSwitchRejected: (actorLabel: string) => string;
  readonly moodSwitchConfigInvalid: (file: string) => string;
  readonly moodSwitchDisabled: string;
  readonly moodSwitchFailed: string;
  readonly moodSwitched: (moodName: string) => string;
  readonly muteRejected: (actorLabel: string, command: string) => string;
  readonly muteSupergroupOnly: string;
  readonly muteChannelTarget: (targetLabel: string) => string;
  readonly muteProtected: (targetLabel: string) => string;
  readonly muteDone: (targetLabel: string, duration: string) => string;
  readonly muteForbidden: (targetLabel: string) => string;
  readonly muteFailed: (targetLabel: string) => string;
  readonly unmuteDone: (targetLabel: string) => string;
  readonly unmuteForbidden: (targetLabel: string) => string;
  readonly unmuteFailed: (targetLabel: string) => string;
  readonly quietAlreadyEnabled: (remainingMinutes: number) => string;
  readonly quietUsage: (minMinutes: number, maxMinutes: number, defaultMinutes: number) => string;
  readonly quietEnabled: (minutes: number) => string;
  readonly quietAlreadyDisabled: string;
  readonly quietDisabled: string;
  readonly proxyAlreadyStopped: string;
  readonly proxyStopped: string;
  readonly proxyUsage: string;
  readonly proxyAlreadyStarted: (activeTargetChatId: number) => string;
  readonly proxyNotInitialized: (targetChatId: number) => string;
  readonly proxyNotGroup: (targetChatId: number) => string;
  readonly proxyUnavailable: (targetChatId: number) => string;
  readonly proxyStarted: (targetChatId: number) => string;
  readonly translateConfigInvalid: (file: string) => string;
  readonly translateNotRunning: (targetLabel: string) => string;
  readonly translateStopped: (targetLabel: string) => string;
  readonly translateAlreadyRunning: (targetLabel: string, language: string) => string;
  readonly translateStarted: (targetLabel: string, language: string) => string;
  readonly unblockRejected: (actorLabel: string) => string;
  readonly unblockCurrentChat: string;
  readonly unblockPersistFailed: string;
  readonly unblockRecorded: (targetLabel: string, persistWarning: string) => string;
  readonly unblockNoManagedChat: (listNote: string) => string;
  readonly unblockPartialFailure: (failedCount: number) => string;
  readonly unblockResult: (listNote: string, unbannedCount: number, failedNote: string) => string;
  readonly copyReverseEffect: string;
  readonly copyNyaEffect: string;
  readonly unknownUser: string;
  readonly adReferenceWarning: (label: string) => string;
  readonly floodMuted: (label: string, messageCount: number, minutes: number) => string;
  readonly lockdownInflux: (windowSeconds: number, joinCount: number) => string;
  readonly lockdownStarted: (influx: string, durationMinutes: number) => string;
  readonly lockdownEnded: (durationMinutes: number) => string;
  readonly verificationCommentExempt: (targetLabel: string) => string;
  readonly verificationBotApproved: (fromLabel: string | undefined, targetLabel: string) => string;
  readonly verificationMemberApproved: (fromLabel: string | undefined, targetLabel: string) => string;
  readonly verificationSelfPassed: (fromLabel: string | undefined) => string;
  readonly verificationAdminOnly: string;
  readonly verificationAdminUnknown: string;
  readonly verificationOtherUser: string;
  readonly verificationCallbackPassed: string;
  readonly verificationCallbackExpired: string;
  readonly verificationUseSelfButton: (selfButton: string, approveButton: string) => string;
  readonly verificationMembershipUnknown: (label: string) => string;
  readonly verificationChatKindUnknown: (label: string) => string;
  readonly verificationFloodKickFailed: (label: string) => string;
  readonly verificationTimeoutKickFailed: (label: string) => string;
  readonly verificationCleanupForbidden: (label: string, messageCount: number, missedCleanup: number) => string;
  readonly verificationCleanupFailed: (label: string, missedCleanup: number) => string;
  readonly verificationFloodKicked: (label: string) => string;
  readonly verificationBotTimeout: (timeout: string, label: string) => string;
  readonly verificationMemberTimeout: (label: string, timeout: string) => string;
  readonly verificationBotReminder: (label: string, timeout: string, approveButton: string) => string;
  readonly verificationMemberReminder: (values: Readonly<{ label: string; timeout: string; selfButton: string; approveButton: string }>) => string;
  readonly verificationReplyReminder: (label: string, timeout: string, selfButton: string) => string;
}
