import type { AtmosphereNotices } from "../../../types/atmosphereNotices";

/** 普通风格通知表；Bot 配置为 normal 或群设置了自定义 AI 人设时使用。 */
export const NOTICE_TEXTS: Readonly<AtmosphereNotices> = {
  verificationCallbackPassed: "验证已通过。",
  verificationCallbackExpired: "验证已失效，请重新加入群后再试。",
  verificationUseSelfButton: (selfButton: string, approveButton: string): string => `请点击「${selfButton}」完成本人的验证；「${approveButton}」仅供管理员代他人验证。`,
  statusChatIdLabel: "• 本群 ID：",
  statusContextUsage: (percent: string): string => `• AI 上下文利用率：${percent}`,
  blockAlreadyRecorded: (warning: string): string => `（原本就在黑名单中${warning}）`,
  blockKicked: (count: number): string => `从 ${count} 个群移出并封禁`,
  unblockNotRecorded: (label: string): string => `${label} 原本就不在永久黑名单中`,
  batchKickAborted: "\n中途无法读取黑白名单，剩余记录未执行处置，请稍后重试。",
  gagChannelEntry: "频道身份请点击下方「发言」按钮，直接 @ 机器人不会显示发言入口。",
  adDetected: (label: string, reason: string): string => `${label} 被判定为广告，理由：${reason}。`,
  adNoManagedChat: (head: string): string => `${head}已加入永久黑名单，但未能在任何群封禁，请管理员检查机器人权限。`,
  adPartialBan: (head: string, enforcedChats: number, failedChats: number): string => `${head}已加入永久黑名单，在 ${enforcedChats} 个群完成封禁，另有 ${failedChats} 个群未成功，请管理员检查权限。`,
  adBanned: (head: string): string => `${head}已加入永久黑名单，并在所有受管群完成封禁。`,
  proxyFailed: (targetChatId: number): string => `转发到 ${targetChatId} 失败，本轮中转已停止。请检查后重新使用 /send 开启。`,
  adConfigInvalid: (file: string): string => `无法读取配置 ${file}，广告检测未开启。请修正配置并重启。`,
  aiConfigInvalid: (file: string): string => `无法读取配置 ${file}，AI 闲聊未开启。请修正配置并重启。`,
  batchKickRejected: "/batch_kick 仅限超级管理员本人使用。",
  batchKickSupergroupOnly: "/batch_kick 仅支持超级群。",
  joinLogUnavailable: "暂时无法读取入群日志，本次未执行处置，请稍后重试。",
  batchKickEmpty: (duration: string): string => `最近 ${duration} 没有新成员记录，本次未踢人，也未写入黑名单。`,
  batchKickResult: (values: Readonly<{ duration: string; recordCount: number; scanned: number; kicked: number; absent: number; protected: number; blocked: number; forbidden: number; failed: number; abortedNotice: string }>): string => `已扫描最近 ${values.duration} 的 ${values.recordCount} 条入群记录中的 ${values.scanned} 条：踢出 ${values.kicked}，已不在群 ${values.absent}，受保护身份跳过 ${values.protected}，黑名单交回封禁 ${values.blocked}，权限不足 ${values.forbidden}，查询或请求失败 ${values.failed}。只踢出，未加入黑名单。${values.abortedNotice}`,
  blockUsage: "用法：/block <用户id|@username> enable 拉黑，/block <用户id|频道id|@username> disable 解除；回复目标时可省略身份。",
  blockRejected: (actorLabel: string): string => `${actorLabel} 没有使用 /block enable 的权限。`,
  blockCurrentChat: "不能将当前群身份作为封禁目标，Telegram 无法提供匿名管理员背后的个人身份。",
  blockProtected: (targetLabel: string): string => `${targetLabel} 是受保护身份，不能加入黑名单。`,
  blockPersistFailed: "（黑名单未能保存，重启后会丢失本次修改，请管理员检查磁盘）",
  blockNoManagedChat: (targetLabel: string, persistWarning: string): string => `已将 ${targetLabel} 加入黑名单${persistWarning}。机器人尚未在任何群担任管理员，当前无法踢出；之后进入受管群时将自动封禁。`,
  blockAllFailed: (targetLabel: string, persistWarning: string): string => `未能在任何群封禁 ${targetLabel}，请管理员检查权限。已加入黑名单${persistWarning}，之后进入受管群时将自动封禁。`,
  blockSkippedHere: (reason: string): string => `本群未封禁（${reason}）；`,
  blockPartialFailure: (failedCount: number): string => `（另有 ${failedCount} 个群未封禁成功，请管理员检查权限）`,
  blockRecorded: (persistWarning: string): string => `，已加入永久黑名单${persistWarning}`,
  blockResult: (values: Readonly<{ skippedHereNote: string; targetLabel: string; actionNote: string; failedNote: string; blocklistNote: string }>): string => `${values.skippedHereNote}${values.targetLabel} 已被${values.actionNote}${values.failedNote}${values.blocklistNote}。`,
  botPermissionUnknown: "暂时无法确认机器人在本群的权限，请稍后重试",
  botNotAdministrator: (permission: string): string => `机器人不是本群管理员，请将其设为管理员并授予「${permission}」权限`,
  botMissingPermission: (permission: string): string => `机器人是本群管理员，但缺少「${permission}」权限，请管理员补充授权`,
  statusTitle: "机器人状态",
  statusProcess: "本机进程：",
  statusModels: "全局模型能力：",
  statusGag: (activeGagSessions: number, capacity: number): string => `• 当前 gag 会话：${activeGagSessions}/${capacity}`,
  statusTranslate: (activeTranslateSessions: number, capacity: number): string => `• 本群翻译人数：${activeTranslateSessions}/${capacity} 人`,
  statusPermissions: "机器人在本群的权限：",
  statusPermissionsUnknown: "• 尚未确认本群权限",
  statusFeatures: "本群功能开关：",
  statusRejected: (actorLabel: string): string => `${actorLabel} 没有查看机器人状态的权限。`,
  actionUsage: "/x 是菜单中的用法说明。请将 x 换成任意 1~2 个中文字，例如 /咬、/贴贴；回复目标消息或加 @username 指定对象。",
  actionMissingTarget: (actionWord: string, command: string): string => `请指定要「${actionWord}」的对象：回复目标消息，或使用 /${command} @username。`,
  actionInvalidTarget: (rawArgument: string, actionWord: string): string => `${rawArgument} 不是完整合法的 Telegram 用户名，无法执行「${actionWord}」。`,
  actionUnknownTarget: (rawUsername: string, actionWord: string): string => `尚未记录 @${rawUsername}，请回复目标消息后执行「${actionWord}」。`,
  actionConflictingTarget: (rawArgument: string, actionWord: string): string => `回复对象与 ${rawArgument} 不一致，请只保留一个「${actionWord}」的目标。`,
  actionSelfTarget: (actionWord: string): string => `不能将机器人自身作为「${actionWord}」的目标。`,
  clearContextRejected: (actorLabel: string): string => `${actorLabel} 没有清空本群 AI 上下文的权限。`,
  clearContextFailed: "本次未能清空全部上下文，请稍后重试。",
  clearContextDone: "本群 AI 上下文已清空，后续对话将重新记录。",
  copyAlreadyRunning: (targetLabel: string): string => `已经在复读 ${targetLabel}。`,
  copyOtherTarget: "已有复读目标，请先使用 /copy stop 再更换。",
  copyStarting: (targetLabel: string, modeDescription: string): string => `正在使用 ${targetLabel} 的头像${modeDescription}，请稍等。`,
  copyAvatarChanged: (targetLabel: string): string => `已使用 ${targetLabel} 的头像。`,
  copyAvatarFailed: (targetLabel: string): string => `头像修改失败，可能是目标没有公开头像或请求受到限流；仍会开始复读 ${targetLabel} 的消息。`,
  copyNotRunning: "当前没有复读目标，无需执行 /copy stop。",
  copyStopped: "复读已停止。",
  copyAvatarRestored: "已恢复默认头像。",
  copyAvatarRestoreFailed: "复读已停止，但头像恢复失败。可能无法获取图片或请求受到限流，请稍后使用 /icon reset 重试。",
  copyCooldown: (remaining: string): string => `copy 类命令仍在冷却，请等待 ${remaining} 后再试。`,
  unknownActor: "当前身份",
  gagRejected: (actorLabel: string, command: string): string => `${actorLabel} 没有使用 /${command} 的权限。`,
  gagGroupOnly: "/gag 和 /ungag 仅支持群聊。",
  gagNotInitialized: "本群尚未接管，请先执行 /init enable。",
  gagMissingRights: (command: string, reason: string): string => `无法执行 /${command}：${reason}。`,
  gagToolTooLong: "用具名称过长，无法容纳 Telegram inline 消息，请缩短后重试。",
  gagCapacity: (capacity: number): string => `当前已达到 ${capacity} 个 gag 会话的上限，请等待已有会话结束。`,
  gagEnding: (targetLabel: string): string => `${targetLabel} 的 gag 会话正在结束，请稍等。`,
  gagExists: (targetLabel: string): string => `${targetLabel} 在本群已有 gag 会话；更换用具前请先对该目标执行 /ungag。`,
  gagTargetAbsent: (targetLabel: string): string => `${targetLabel} 不在本群，无法执行 gag。`,
  gagMembershipUnknown: (targetLabel: string): string => `暂时无法确认 ${targetLabel} 是否仍在本群，请稍后重试。`,
  ungagEnding: (targetLabel: string): string => `${targetLabel} 的 gag 会话正在结束，请稍等。`,
  ungagStarting: (targetLabel: string): string => `${targetLabel} 的 gag 会话仍在启动，请稍等。`,
  ungagAbsent: (targetLabel: string): string => `${targetLabel} 在本群没有 gag 会话。`,
  gagPublicNotice: (values: Readonly<{ targetLabel: string; tool: string; durationMinutes: number; channelEntry: string }>): string => `${values.targetLabel} 已设置 gag，用具为 ${values.tool}。${values.durationMinutes} 分钟内将删除其文本消息和带文字说明的媒体消息，无文字的媒体不受影响。${values.channelEntry}`,
  gagSpeakNotice: (targetLabel: string): string => `${targetLabel}，此发言入口仅你可见，请点击下方「发言」按钮。`,
  gagExpired: "限制时间已到",
  gagRemoved: "限制已提前解除",
  gagEndedNotice: (reasonText: string, targetLabel: string, tool: string): string => `${reasonText}，${targetLabel} 的 ${tool} 已取下，可以正常发言。`,
  iconRestoring: "正在恢复默认头像，请稍等。",
  iconRestored: "已恢复默认头像。",
  iconRestoreFailed: "默认头像恢复失败，可能无法获取图片或请求受到限流，请稍后重试。",
  iconStarting: (targetLabel: string): string => `正在获取并使用 ${targetLabel} 的头像，请稍等。`,
  iconChanged: (targetLabel: string): string => `已使用 ${targetLabel} 的头像。`,
  iconFailed: (targetLabel: string): string => `获取或使用 ${targetLabel} 的头像失败，可能是目标没有公开头像或请求受到限流，请稍后重试。`,
  inlineRateLimitTitle: "请求过于频繁",
  inlineRateLimitDescription: (windowSeconds: number, maxCalls: number): string => `每 ${windowSeconds} 秒最多接受 ${maxCalls} 次请求，请稍后再试`,
  inlineRateLimitBody: (windowSeconds: number, maxCalls: number): string => `请求过于频繁，每 ${windowSeconds} 秒最多接受 ${maxCalls} 次，请稍后再试。`,
  moodQueryConfigInvalid: (file: string): string => `无法读取配置 ${file}，本次未查询心情。请修正配置并重启。`,
  moodQueryDisabled: "本群 AI 闲聊未开启，无法查询心情。",
  moodQueryFailed: "未及时取得当前心情，请稍后重试。",
  moodCurrent: (moodName: string): string => `本群 AI 当前心情是「${moodName}」。`,
  moodSwitchRejected: (actorLabel: string): string => `${actorLabel} 没有切换本群 AI 心情的权限。`,
  moodSwitchConfigInvalid: (file: string): string => `无法读取配置 ${file}，本次未切换心情。请修正配置并重启。`,
  moodSwitchDisabled: "本群 AI 闲聊未开启，无法切换心情。",
  moodSwitchFailed: "未能确认新心情，请稍后重试。",
  moodSwitched: (moodName: string): string => `已重新抽取，本群 AI 当前心情是「${moodName}」。`,
  muteRejected: (actorLabel: string, command: string): string => `${actorLabel} 没有使用 /${command} 的权限。`,
  muteSupergroupOnly: "Telegram 仅支持在超级群限制成员发言。",
  muteChannelTarget: (targetLabel: string): string => `${targetLabel} 是频道身份，无法通过成员禁言接口限制；Telegram 不提供其背后的个人身份。`,
  muteProtected: (targetLabel: string): string => `${targetLabel} 是受保护身份，不能通过此命令禁言。`,
  muteDone: (targetLabel: string, duration: string): string => `已禁言 ${targetLabel}，时长 ${duration}，到期自动解除；管理员可使用 /unmute 提前解除。`,
  muteForbidden: (targetLabel: string): string => `未能禁言 ${targetLabel}：机器人缺少「限制与封禁成员」权限，或目标为管理员，请管理员检查。`,
  muteBotLacksRights: (targetLabel: string, reason: string): string => `未能禁言 ${targetLabel}：${reason}。`,
  muteFailed: (targetLabel: string): string => `Telegram 请求未完成，未能禁言 ${targetLabel}，请稍后重试。`,
  unmuteDone: (targetLabel: string): string => `已解除 ${targetLabel} 的禁言。`,
  unmuteForbidden: (targetLabel: string): string => `未能解除 ${targetLabel} 的禁言：机器人缺少「限制与封禁成员」权限，或目标为管理员，请管理员检查。`,
  unmuteBotLacksRights: (targetLabel: string, reason: string): string => `未能解除 ${targetLabel} 的禁言：${reason}。`,
  unmuteFailed: (targetLabel: string): string => `Telegram 请求未完成，尚未解除 ${targetLabel} 的禁言，请稍后重试。`,
  quietAlreadyEnabled: (remainingMinutes: number): string => `当前静默还剩约 ${remainingMinutes} 分钟，不能叠加；重新设置前请先执行 /unquiet。`,
  quietUsage: (minMinutes: number, maxMinutes: number, defaultMinutes: number): string => `/quiet 后可指定分钟数（${minMinutes}~${maxMinutes}），省略时为 ${defaultMinutes} 分钟。`,
  quietEnabled: (minutes: number): string => `已静默 ${minutes} 分钟，期间不主动插话或复读；回复或 @ 机器人仍可对话。`,
  quietAlreadyDisabled: "当前未处于静默状态。",
  quietDisabled: "静默已解除，恢复自动回复。",
  proxyAlreadyStopped: "当前没有正在进行的转发。",
  proxyStopped: "转发已停止。",
  proxyUsage: "请使用 /send <群组id> 开始转发，或使用 /send finish 停止。",
  proxyAlreadyStarted: (activeTargetChatId: number): string => `当前正在转发到 ${activeTargetChatId}，请先执行 /send finish。`,
  proxyNotInitialized: (targetChatId: number): string => `尚未接管 ${targetChatId}，请先在目标群执行 /init enable。`,
  proxyNotGroup: (targetChatId: number): string => `${targetChatId} 不是群组，请检查 id。`,
  proxyUnavailable: (targetChatId: number): string => `无法连接聊天 ${targetChatId}，请检查 id 及机器人是否已加入。`,
  proxyStarted: (targetChatId: number): string => `此处后续消息将转发到 ${targetChatId}，结束时请执行 /send finish。`,
  proxyTtsUsage: (textMaxChars: number, toneMaxChars: number): string => `语音请求格式不对。请把 { "type": "tts", "tone": "语气（可省，不超过 ${toneMaxChars} 字）", "text": "台词（不超过 ${textMaxChars} 字）" } 整条作为代码块发送。`,
  proxyTtsUnconfigured: "未配置语音合成（config/agent.json 的 agent.tts），无法发送语音。",
  proxyTtsBusy: "正在处理的请求过多，请稍后再发这条语音。",
  proxyTtsFailed: (targetChatId: number): string => `语音合成或发送到 ${targetChatId} 失败，转发会话仍在进行。`,
  translateConfigInvalid: (file: string): string => `配置 ${file} 缺失或无效，无法翻译。请修正配置并重启。`,
  translateNotRunning: (targetLabel: string): string => `${targetLabel} 没有正在进行的翻译。`,
  translateStopped: (targetLabel: string): string => `已停止为 ${targetLabel} 翻译，其他会话继续。`,
  translateAlreadyRunning: (targetLabel: string, language: string): string => `正在将 ${targetLabel} 的文字翻译成${language}；更换语言前请回复目标执行 /translate stop。`,
  translateStarted: (targetLabel: string, language: string): string => `开始将 ${targetLabel} 的文字翻译成${language}，停止请使用 /translate stop。`,
  unblockRejected: (actorLabel: string): string => `${actorLabel} 没有使用 /block disable 的权限。`,
  unblockCurrentChat: "不能将当前群身份作为解封目标，Telegram 无法提供匿名管理员背后的个人身份。",
  unblockPersistFailed: "（黑名单修改未能保存，重启后目标仍会在名单中，请管理员检查磁盘）",
  unblockRecorded: (targetLabel: string, persistWarning: string): string => `已将 ${targetLabel} 移出永久黑名单${persistWarning}`,
  unblockNoManagedChat: (listNote: string): string => `${listNote}；机器人尚未在任何群担任管理员，无法解除各群封禁。`,
  unblockPartialFailure: (failedCount: number): string => `（另有 ${failedCount} 个群未解封成功，请管理员检查权限）`,
  unblockResult: (listNote: string, unbannedCount: number, failedNote: string): string => `${listNote}，已在 ${unbannedCount} 个群解除封禁${failedNote}。`,
  copyReverseEffect: "，之后会倒序复读目标的纯文字消息",
  copyNyaEffect: "，之后会在目标的纯文字消息末尾追加喵~",
  unknownUser: "这个用户",
  adReferenceWarning: (label: string): string => `${label}，请勿回复、引用或转发广告相关内容。`,
  floodMuted: (label: string, messageCount: number, minutes: number): string => `${label} 一分钟内发送了 ${messageCount} 条消息，已禁言 ${minutes} 分钟。`,
  lockdownInflux: (windowSeconds: number, joinCount: number): string => `${windowSeconds} 秒内有 ${joinCount} 名成员入群`,
  lockdownStarted: (influx: string, durationMinutes: number): string => `${influx}，触发防冲群限制，暂停普通成员邀请新人 ${durationMinutes} 分钟。`,
  lockdownEnded: (durationMinutes: number): string => `${durationMinutes} 分钟限制已结束，普通成员已恢复邀请权限。`,
  verificationCommentExempt: (targetLabel: string): string => `${targetLabel} 已通过帖子评论身份检查，免除入群验证，欢迎加入。`,
  verificationBotApproved: (fromLabel: string | undefined, targetLabel: string): string => `管理员 ${fromLabel} 已为机器人 ${targetLabel} 通过入群验证。`,
  verificationMemberApproved: (fromLabel: string | undefined, targetLabel: string): string => `管理员 ${fromLabel} 已为 ${targetLabel} 通过入群验证，欢迎加入。`,
  verificationSelfPassed: (fromLabel: string | undefined): string => `${fromLabel} 已通过入群验证，欢迎加入。`,
  verificationAdminOnly: "仅本群管理员可以代他人点击「通过」。",
  verificationAdminUnknown: "暂时无法确认你的管理员身份，请稍后重试。",
  verificationOtherUser: "这不是你的验证按钮。",
  verificationMembershipUnknown: (label: string): string => `无法确认 ${label} 是否仍在群内，本次未踢人，将继续重试。请管理员检查网络和成员查询权限。`,
  verificationChatKindUnknown: (label: string): string => `无法确认聊天类型，本次未对 ${label} 执行踢人，将继续重试。请管理员检查网络。`,
  verificationFloodKickFailed: (label: string): string => `${label} 未完成验证并触发刷屏限制，但踢出失败，请管理员检查封禁权限。`,
  verificationTimeoutKickFailed: (label: string): string => `${label} 超时未验证，但踢出失败。请管理员检查封禁权限，必要时手动处理。`,
  verificationCleanupForbidden: (label: string, messageCount: number, missedCleanup: number): string => `${label} 未通过验证，已被踢出；共 ${messageCount} 条验证消息中仍有 ${missedCleanup} 条无法删除，请管理员检查删除消息权限。`,
  verificationCleanupFailed: (label: string, missedCleanup: number): string => `${label} 未通过验证，已被踢出；仍有 ${missedCleanup} 条验证消息未清理，请检查网络。`,
  verificationFloodKicked: (label: string): string => `${label} 未完成验证并触发刷屏限制，已被踢出。`,
  verificationBotTimeout: (timeout: string, label: string): string => `${timeout} 内没有管理员为机器人 ${label} 通过验证，已将其踢出。`,
  verificationMemberTimeout: (label: string, timeout: string): string => `${label} 未在 ${timeout} 内完成验证，已被踢出。`,
  verificationBotReminder: (label: string, timeout: string, approveButton: string): string => `机器人 ${label} 无法自行点击验证按钮，请管理员在 ${timeout} 内点击「${approveButton}」通过验证，否则将被踢出。`,
  verificationMemberReminder: (values: Readonly<{ label: string; timeout: string; selfButton: string; approveButton: string }>): string => `${values.label}，请在 ${values.timeout} 内点击下方「${values.selfButton}」完成验证，管理员也可点击「${values.approveButton}」代为通过；超时将被踢出。`,
  verificationReplyReminder: (label: string, timeout: string, selfButton: string): string => `${label}，请在 ${timeout} 内点击下方「${selfButton}」完成验证，超时将被踢出。`,
};
