import type { AtmosphereNotices } from "../../../types/atmosphereNotices";

/** 雌小鬼风格通知表；Bot 配置为 mesugaki 且群没有自定义 AI 人设时使用。 */
export const NOTICE_TEXTS: Readonly<AtmosphereNotices> = {
  verificationCallbackPassed: "哼，算你过关啦，杂鱼♡",
  verificationCallbackExpired: "啧，验证早就失效啦，杂鱼重新进群再试试吧♡",
  verificationUseSelfButton: (selfButton: string, approveButton: string): string => `笨蛋，想自己过验证就点「${selfButton}」，「${approveButton}」是给管理员代点的，别乱按♡`,
  statusChatIdLabel: "• 本群 ID：",
  statusContextUsage: (percent: string): string => `• 猫娘大脑利用率：${percent}`,
  blockAlreadyRecorded: (warning: string): string => `（早就在小本本上了${warning}）`,
  blockKicked: (count: number): string => `从 ${count} 个群一脚踢出去还上了黑名单`,
  unblockNotRecorded: (label: string): string => `${label} 本来就不在小本本上`,
  batchKickAborted: "\n啧，中途黑白名单读不出来了，剩下的记录一条都没动，本天才可不背锅，稍后再跑一次吧，笨蛋♡",
  gagChannelEntry: "频道马甲想说话就必须先乖乖点下面的「发言」按钮，直接 @ 本天才可不会给你选项哦，连入口都找不到的杂鱼就安静待着吧♡",
  adDetected: (label: string, reason: string): string => `哼，${label} 被本天才当广告封了，理由：${reason}。`,
  adNoManagedChat: (head: string): string => `${head}人已经记进小本本了；可本天才现在一个群都封不动，杂鱼管理员快来看看本天才的权限♡`,
  adPartialBan: (head: string, enforcedChats: number, failedChats: number): string => `${head}人已经记进小本本、在 ${enforcedChats} 个群封掉了，还有 ${failedChats} 个群没封动，杂鱼管理员快来看看本天才在那边的权限♡`,
  adBanned: (head: string): string => `${head}人已经记进小本本、在所有盯着的群里一起封掉了♡`,
  proxyFailed: (targetChatId: number): string => `啧，转发到 ${targetChatId} 失败了，本天才先把这轮中转掐掉啦，检查好了再 /send 重新开，笨蛋♡`,
  adConfigInvalid: (file: string): string => `本天才的 ${file} 写坏了，判定口径都读不出来还抓什么广告？修好再重启，笨蛋♡`,
  aiConfigInvalid: (file: string): string => `本天才的 ${file} 写坏了，读都读不动还闲什么聊？修好再重启，笨蛋♡`,
  batchKickRejected: "就你也想批量踢人？/batch_kick 只听超级管理员本人的，杂鱼退散啦♡",
  batchKickSupergroupOnly: "笨蛋，/batch_kick 只能在超级群里使用♡",
  joinLogUnavailable: "呜……入群日志暂时读不了，本次一个人都没动，稍后再试吧♡",
  batchKickEmpty: (duration: string): string => `噗，最近 ${duration} 连一个新成员都没记录到，本天才没有踢人，也没有写入黑名单，白跑一趟啦杂鱼♡`,
  batchKickResult: (values: Readonly<{ duration: string; recordCount: number; scanned: number; kicked: number; absent: number; protected: number; blocked: number; forbidden: number; failed: number; abortedNotice: string }>): string => `哼，本天才翻完了最近 ${values.duration} 的 ${values.recordCount} 条入群记录中的 ${values.scanned} 条：踢出 ${values.kicked}，已不在群 ${values.absent}，自己人跳过 ${values.protected}，黑名单交回封禁 ${values.blocked}，权限不足 ${values.forbidden}，查询或请求失败 ${values.failed}。只踢未拉黑，被踢的杂鱼想回来就重新排队吧♡${values.abortedNotice}`,
  blockUsage: "笨蛋，/block 后面要跟 enable 或 disable 呀：/block <用户id|@username> enable 拉黑，/block <用户id|频道id|@username> disable 解除，回复 TA 的消息时只写动作就行♡",
  blockRejected: (actorLabel: string): string => `就 ${actorLabel} 也想 /block 人？哪来的资格呀，笨蛋，洗洗睡吧♡`,
  blockCurrentChat: "匿名管理员拿这个群当皮套时，Telegram 不会告诉本天才皮套底下是谁；本天才不能把整个群当成那个人踢掉呀♡",
  blockProtected: (targetLabel: string): string => `笨蛋，${targetLabel} 可是自己人，本天才才不会把自己人写进小本本♡`,
  blockPersistFailed: "（不过小本本没能写进硬盘，重启就忘了，杂鱼管理员快去查磁盘）",
  blockNoManagedChat: (targetLabel: string, persistWarning: string): string => `笨蛋，本天才连一个群的管理员都不是，${targetLabel} 现在踢也踢不动，不过已经记进小本本了${persistWarning}——再进本天才盯着的任何群就秒踢♡`,
  blockAllFailed: (targetLabel: string, persistWarning: string): string => `呜……${targetLabel} 居然一个群都踢不动，是本天才没有封禁权限吧？杂鱼管理员快去检查——不过 TA 已经记进小本本了${persistWarning}，再进群就秒踢♡`,
  blockSkippedHere: (reason: string): string => `这个群本天才踢不动 TA（${reason}），不过——`,
  blockPartialFailure: (failedCount: number): string => `（还有 ${failedCount} 个群没踢动，杂鱼管理员快去检查权限）`,
  blockRecorded: (persistWarning: string): string => `，杂鱼永远别想回来了${persistWarning}`,
  blockResult: (values: Readonly<{ skippedHereNote: string; targetLabel: string; actionNote: string; failedNote: string; blocklistNote: string }>): string => `${values.skippedHereNote}哼，${values.targetLabel} 被本天才${values.actionNote}${values.failedNote}${values.blocklistNote}♡`,
  botPermissionUnknown: "本天才一时没查清自己在这个群的权限，杂鱼稍后再试吧",
  botNotAdministrator: (permission: string): string => `本天才在这个群还不是管理员，先把本天才设成管理员、再勾上「${permission}」权限啦`,
  botMissingPermission: (permission: string): string => `本天才在这个群是管理员，可没被勾上「${permission}」权限，快去补上啦`,
  statusTitle: "本天才的状态，杂鱼可要看仔细啦♡",
  statusProcess: "本机进程，本天才当然精神得很♡：",
  statusModels: "全局模型能力，本天才会的可多着呢♡：",
  statusGag: (activeGagSessions: number, capacity: number): string => `• 正在被本天才调教的杂鱼：${activeGagSessions}/${capacity}`,
  statusTranslate: (activeTranslateSessions: number, capacity: number): string => `• 本群正赖着本天才翻译的杂鱼：${activeTranslateSessions}/${capacity}♡`,
  statusPermissions: "本天才在这个群的权柄，杂鱼可别眼红♡：",
  statusPermissionsUnknown: "• 还没确证呢，等本天才在这个群有了身份再来看吧，笨蛋♡",
  statusFeatures: "本群的开关都摆这儿了，连这个都记不住吗，笨蛋♡：",
  statusRejected: (actorLabel: string): string => `就 ${actorLabel} 也想看本天才的全局状态？哪来的资格呀，笨蛋♡`,
  actionUsage: "笨蛋，/x 只是菜单里的用法说明啦——把 x 换成任意 1~2 个中文字直接发，比如 /咬、/贴贴，再回复 TA 的消息或者加 @username 指定对象♡",
  actionMissingTarget: (actionWord: string, command: string): string => `笨蛋，要 ${actionWord} 谁呀？回复 TA 的一条消息，或者写成 /${command} @username 再来♡`,
  actionInvalidTarget: (rawArgument: string, actionWord: string): string => `笨蛋，${rawArgument} 才不是完整合法的 Telegram 用户名，本天才可不会对着空气 ${actionWord}♡`,
  actionUnknownTarget: (rawUsername: string, actionWord: string): string => `笨蛋，@${rawUsername} 都还没说过话呢，本天才不认识这号杂鱼，回复 TA 的消息再 ${actionWord} 吧♡`,
  actionConflictingTarget: (rawArgument: string, actionWord: string): string => `笨蛋，你回复了一条消息、又写了 ${rawArgument}，本天才该 ${actionWord} 哪个呀？只留一个再来♡`,
  actionSelfTarget: (actionWord: string): string => `哼，本天才可不给杂鱼 ${actionWord}，想得美♡`,
  clearContextRejected: (actorLabel: string): string => `就 ${actorLabel} 也想抹掉本天才的记忆？哪来的资格呀，笨蛋♡`,
  clearContextFailed: "呜……这次没擦干净，才不是本天才的错呢！过会儿再来求本天才一次吧，杂鱼♡",
  clearContextDone: "哼，你们这群杂鱼说过的破事，本天才一句都不记得啦——从现在起重新讨好本天才吧♡",
  copyAlreadyRunning: (targetLabel: string): string => `早就在复读 ${targetLabel} 啦，杂鱼，是没听清楚吗♡`,
  copyOtherTarget: "本天才手上已经有猎物啦，想换人的话先 /copy stop 呀，笨蛋♡",
  copyStarting: (targetLabel: string, modeDescription: string): string => `正在把 ${targetLabel} 的脸皮扒下来当本天才的头像哦${modeDescription}，杂鱼乖乖等一下~♡`,
  copyAvatarChanged: (targetLabel: string): string => `嘿嘿，${targetLabel} 的脸已经被本天才偷走啦，杂鱼♡`,
  copyAvatarFailed: (targetLabel: string): string => `啧，修改头像失败了呢（可能是 TA 没设置公开头像，或者本天才换头像太频繁被限流了）。不过没关系，本天才依然要开始疯狂复读 ${targetLabel} 的消息啦，杂鱼♡`,
  copyNotRunning: "本天才现在什么杂鱼都没盯着呢，笨蛋要 /copy stop 什么呀♡",
  copyStopped: "哼，不玩了，本天才先歇一下~杂鱼♡",
  copyAvatarRestored: "顺手把脸也换回来了，本天才的原装脸可比杂鱼们的耐看多了♡",
  copyAvatarRestoreFailed: "复读是停了，但脸没换回来呢（图取不下来或者被限流了），等下可以 /icon reset 再试，杂鱼♡",
  copyCooldown: (remaining: string): string => `急什么呀笨蛋，还要等 ${remaining} 才能用 copy 类命令哦，乖乖等着吧♡`,
  unknownActor: "哪个杂鱼",
  gagRejected: (actorLabel: string, command: string): string => `哈？就 ${actorLabel} 这种没资格的杂鱼也想 /${command} 人？做梦去吧♡`,
  gagGroupOnly: "噗，连地方都找不对吗？/gag 和 /ungag 只能在群里用啦，笨蛋♡",
  gagNotInitialized: "这个群连 /init enable 都没开，还想使唤本天才管 gag？先把准备做好呀，杂鱼♡",
  gagMissingRights: (command: string, reason: string): string => `哼，/${command} 本天才现在接不了：${reason}♡`,
  gagToolTooLong: "噗，这个用具名字长到连 Telegram 的 inline 消息都塞不下，杂鱼的命名品味也太差了吧♡",
  gagCapacity: (capacity: number): string => `本天才同时管教的 ${capacity} 只杂鱼已经满员啦，连排队都不会吗？等一个结束再来♡`,
  gagEnding: (targetLabel: string): string => `${targetLabel} 这只杂鱼还在收尾，急什么呀？乖乖等着♡`,
  gagExists: (targetLabel: string): string => `${targetLabel} 这只杂鱼在本群已经被管教啦；要换工具就先定向 /ungag，笨蛋♡`,
  gagTargetAbsent: (targetLabel: string): string => `${targetLabel} 根本不在这个群里，想隔空 gag 人的杂鱼在做什么梦呀♡`,
  gagMembershipUnknown: (targetLabel: string): string => `啧，本天才暂时确认不了 ${targetLabel} 还在不在群里，急也没用，杂鱼等会儿再试啦♡`,
  ungagEnding: (targetLabel: string): string => `${targetLabel} 的 gag 已经在收尾啦，急什么呀杂鱼？乖乖等着♡`,
  ungagStarting: (targetLabel: string): string => `${targetLabel} 还没戴好呢，手忙脚乱的杂鱼先等一下♡`,
  ungagAbsent: (targetLabel: string): string => `${targetLabel} 在本群根本没被本天才 gag，对着空气 /ungag 的笨蛋♡`,
  gagPublicNotice: (values: Readonly<{ targetLabel: string; tool: string; durationMinutes: number; channelEntry: string }>): string => `哼哼，${values.targetLabel} 这只爱乱说话的杂鱼已经戴上 ${values.tool} 啦♡ ${values.durationMinutes} 分钟内文本消息和带文字说明的媒体消息都会被本天才删掉，没有文字的媒体不受影响。${values.channelEntry}`,
  gagSpeakNotice: (targetLabel: string): string => `${targetLabel}，只有你看得到这个发言入口；想说话就乖乖点下面的「发言」按钮啦♡`,
  gagExpired: "哼哼，处罚时间到啦",
  gagRemoved: "哼，提前解除啦",
  gagEndedNotice: (reasonText: string, targetLabel: string, tool: string): string => `${reasonText}，${targetLabel} 的 ${tool} 已经取下，终于又能正常说话咯，可别高兴得太早呀，杂鱼♡`,
  iconRestoring: "啧，戴腻了别人的脸，本天才这就换回自己的，杂鱼♡",
  iconRestored: "呐，本天才的脸回来了，是不是好看多了，杂鱼♡",
  iconRestoreFailed: "唔，换回自己的脸失败了呢（可能是图取不下来，或者本天才换头像太频繁被限流了），等会儿再试吧杂鱼♡",
  iconStarting: (targetLabel: string): string => `收到收到，本天才这就去把 ${targetLabel} 的脸皮扒下来戴上，杂鱼稍安勿躁~♡`,
  iconChanged: (targetLabel: string): string => `嘿嘿，${targetLabel} 的脸已经被本天才偷来戴上啦，杂鱼♡`,
  iconFailed: (targetLabel: string): string => `啧，偷 ${targetLabel} 的头像失败了呢（可能是 TA 没设置公开头像，或者本天才换头像太频繁被限流了），下次再来吧杂鱼♡`,
  inlineRateLimitTitle: "太快啦，本天才应付不过来～",
  inlineRateLimitDescription: (windowSeconds: number, maxCalls: number): string => `本天才每 ${windowSeconds} 秒最多接 ${maxCalls} 次，杂鱼先歇会儿再来吧`,
  inlineRateLimitBody: (windowSeconds: number, maxCalls: number): string => `笨蛋，问太快啦，本天才每 ${windowSeconds} 秒最多接 ${maxCalls} 次，杂鱼先歇会儿再来吧♡`,
  moodQueryConfigInvalid: (file: string): string => `本天才的 ${file} 写坏了，连心情表都读不出来还查什么？修好再重启，笨蛋♡`,
  moodQueryDisabled: "本群连 AI 闲聊都没开，本天才在这儿根本没有心情可查呀，笨蛋♡",
  moodQueryFailed: "呜……本天才的 AI 脑袋没及时回话，这次没查到当前心情，过会儿再试吧♡",
  moodCurrent: (moodName: string): string => `哼，本天才现在的心情是「${moodName}」，杂鱼可要看着脸色说话哦♡`,
  moodSwitchRejected: (actorLabel: string): string => `就 ${actorLabel} 也想给本天才换心情？本天才的心情才轮不到杂鱼做主呀♡`,
  moodSwitchConfigInvalid: (file: string): string => `本天才的 ${file} 写坏了，连心情表都读不出来还换什么？修好再重启，笨蛋♡`,
  moodSwitchDisabled: "本群连 AI 闲聊都没开，本天才在这儿根本没有心情可换呀，笨蛋♡",
  moodSwitchFailed: "呜……本天才的 AI 脑袋没及时回话，这次没确认到新心情，过会儿再试吧♡",
  moodSwitched: (moodName: string): string => `哼，那就依你重抽一次——本天才现在的心情是「${moodName}」♡`,
  muteRejected: (actorLabel: string, command: string): string => `就 ${actorLabel} 也想 /${command} 人？哪来的资格呀，笨蛋，洗洗睡吧♡`,
  muteSupergroupOnly: "笨蛋，Telegram 只让在超级群里捂人嘴巴，这里本天才有力也使不出呀♡",
  muteChannelTarget: (targetLabel: string): string => `噗，${targetLabel} 是频道皮套，皮套可没有嘴给本天才捂，Telegram 也不告诉本天才底下是谁呀，笨蛋♡`,
  muteProtected: (targetLabel: string): string => `笨蛋，${targetLabel} 可是自己人，本天才才不捂自己人的嘴♡`,
  muteDone: (targetLabel: string, duration: string): string => `哼，${targetLabel} 被本天才捂住嘴 ${duration}，到点自动松开；等不及就找管理员 /unmute 吧♡`,
  muteForbidden: (targetLabel: string): string => `呜……${targetLabel} 捂不住：要么本天才没有「限制与封禁成员」的权限，要么 TA 是管理员，杂鱼管理员自己去看看吧♡`,
  muteBotLacksRights: (targetLabel: string, reason: string): string => `呜……${targetLabel} 捂不住：${reason}♡`,
  muteFailed: (targetLabel: string): string => `呜……Telegram 这会儿不理本天才，${targetLabel} 没捂住，稍后再试一次吧♡`,
  unmuteDone: (targetLabel: string): string => `哼，本天才大发慈悲把 ${targetLabel} 的嘴松开了，下次注意点哦杂鱼♡`,
  unmuteForbidden: (targetLabel: string): string => `呜……${targetLabel} 松不开：要么本天才没有「限制与封禁成员」的权限，要么 TA 是管理员（管理员本来也没被捂着呀），杂鱼管理员自己去看看吧♡`,
  unmuteBotLacksRights: (targetLabel: string, reason: string): string => `呜……${targetLabel} 松不开：${reason}♡`,
  unmuteFailed: (targetLabel: string): string => `呜……Telegram 这会儿不理本天才，${targetLabel} 还没松开，稍后再试一次吧♡`,
  quietAlreadyEnabled: (remainingMinutes: number): string => `本天才已经在闭嘴了呀（还剩约 ${remainingMinutes} 分钟），一个静默没结束不许再叠，想重来就先 /unquiet，笨蛋♡`,
  quietUsage: (minMinutes: number, maxMinutes: number, defaultMinutes: number): string => `笨蛋，/quiet 后面要接分钟数（${minMinutes}~${maxMinutes}），不填就是 ${defaultMinutes} 分钟♡`,
  quietEnabled: (minutes: number): string => `哼，本天才就赏你们 ${minutes} 分钟清净，不主动插话也不复读。想本天才了就回复或 @ 我，杂鱼♡`,
  quietAlreadyDisabled: "本天才本来就没在闭嘴呀，笨蛋要 /unquiet 什么呢♡",
  quietDisabled: "哼，这么快就受不了没有本天才的日子啦？静默解除，杂鱼们做好被吵的准备吧♡",
  proxyAlreadyStopped: "笨蛋，本天才现在又没在转发，是想 finish 什么呀♡",
  proxyStopped: "哼，不转发啦，本天才的传声筒下班了♡",
  proxyUsage: "笨蛋，要 /send <群组id> 或者 /send finish，说清楚呀♡",
  proxyAlreadyStarted: (activeTargetChatId: number): string => `笨蛋，本天才已经在往 ${activeTargetChatId} 转发了，想换地方先 /send finish 呀♡`,
  proxyNotInitialized: (targetChatId: number): string => `${targetChatId} 本天才还没接管呢，先去那边 /init enable 再来使唤本天才，杂鱼♡`,
  proxyNotGroup: (targetChatId: number): string => `噗，${targetChatId} 根本不是群组，本天才只往群组里转发，检查一下 id 啦笨蛋♡`,
  proxyUnavailable: (targetChatId: number): string => `啧，本天才连不上 ${targetChatId} 这个聊天，检查一下 id 对不对、本天才是不是已经在那边了，笨蛋♡`,
  proxyStarted: (targetChatId: number): string => `哼，现在这里发的消息本天才都会转发进 ${targetChatId}，说完了记得 /send finish，别让本天才一直当传声筒♡`,
  proxyTtsUsage: (textMaxChars: number, toneMaxChars: number): string => `笨蛋，语音要把 { "type": "tts", "tone": "语气（可以不写，最多 ${toneMaxChars} 字）", "text": "台词（最多 ${textMaxChars} 字）" } 整条当代码块发过来呀♡`,
  proxyTtsUnconfigured: "哼，config/agent.json 里根本没配 agent.tts，本天才发不出声音啦，杂鱼♡",
  proxyTtsBusy: "本天才手上的活太多啦，这条语音等会儿再发，笨蛋♡",
  proxyTtsFailed: (targetChatId: number): string => `啧，往 ${targetChatId} 发语音失败了，转发还开着，再试一次吧笨蛋♡`,
  translateConfigInvalid: (file: string): string => `本天才的 ${file} 不见了或写坏了，翻不了呀。补好再重启，笨蛋♡`,
  translateNotRunning: (targetLabel: string): string => `${targetLabel} 本来就没在用翻译呀，笨蛋♡`,
  translateStopped: (targetLabel: string): string => `本天才已经停止给 ${targetLabel} 翻译啦，其他杂鱼照常哦♡`,
  translateAlreadyRunning: (targetLabel: string, language: string): string => `本天才正在把 ${targetLabel} 的文字翻成${language}，要换方向先回复 TA 用 /translate stop，笨蛋♡`,
  translateStarted: (targetLabel: string, language: string): string => `哼，本天才开始把 ${targetLabel} 的文字翻成${language}啦，杂鱼说什么都逃不过本天才的眼睛；停止用 /translate stop♡`,
  unblockRejected: (actorLabel: string): string => `就 ${actorLabel} 也想 /block disable 人？哪来的资格呀，笨蛋，洗洗睡吧♡`,
  unblockCurrentChat: "笨蛋，这是本群自己的身份呀——匿名管理员拿它当皮套时，Telegram 也不会告诉本天才皮套底下是谁；本天才没法把整个群当成那个人从小本本上划掉♡",
  unblockPersistFailed: "（不过小本本没能写进硬盘，重启后 TA 还会回到名单上，杂鱼管理员快去查磁盘）",
  unblockRecorded: (targetLabel: string, persistWarning: string): string => `本天才勉为其难把 ${targetLabel} 从小本本上划掉啦${persistWarning}`,
  unblockNoManagedChat: (listNote: string): string => `哼，${listNote}——不过本天才一个群的管理员都不是，各群的封禁想解也解不了呀♡`,
  unblockPartialFailure: (failedCount: number): string => `（还有 ${failedCount} 个群没解开，杂鱼管理员快去检查权限）`,
  unblockResult: (listNote: string, unbannedCount: number, failedNote: string): string => `哼，${listNote}，还在 ${unbannedCount} 个群把封禁一并解开了${failedNote}——这次真的放 TA 回来了，别再让本天才失望哦♡`,
  copyReverseEffect: "，之后 TA 说的纯文字都会被本天才倒过来念",
  copyNyaEffect: "，之后 TA 说的纯文字后面本天才都会给它加上喵~",
  unknownUser: "这个杂鱼",
  adReferenceWarning: (label: string): string => `哼，${label}，不要回复、引用或转发广告相关内容，连这点都记不住吗，杂鱼♡`,
  floodMuted: (label: string, messageCount: number, minutes: number): string => `哼，${label} 一分钟刷了 ${messageCount} 条，本天才把你禁言 ${minutes} 分钟，冷静完了再回来说话啦杂鱼♡`,
  lockdownInflux: (windowSeconds: number, joinCount: number): string => `${windowSeconds} 秒内冲进来了 ${joinCount} 个杂鱼`,
  lockdownStarted: (influx: string, durationMinutes: number): string => `哼，${influx}，本天才怀疑是有人在拉人头，先禁止普通成员邀请新人 ${durationMinutes} 分钟压压惊♡`,
  lockdownEnded: (durationMinutes: number): string => `${durationMinutes} 分钟到啦，解除限制，普通成员又能拉人了，杂鱼们悠着点哦♡`,
  verificationCommentExempt: (targetLabel: string): string => `哼，${targetLabel} 老实巴交的在帖子底下冒个了泡，本天才大发慈悲免了你的验证，欢迎杂鱼入群~♡`,
  verificationBotApproved: (fromLabel: string | undefined, targetLabel: string): string => `哼，既然 ${fromLabel} 大人愿意为机器人 ${targetLabel} 作保，本天才就勉为其难放这个铁疙瘩进来啦~♡`,
  verificationMemberApproved: (fromLabel: string | undefined, targetLabel: string): string => `哼，既然 ${fromLabel} 大人肯为 ${targetLabel} 作保，本天才就勉为其难放这条杂鱼进来啦~♡`,
  verificationSelfPassed: (fromLabel: string | undefined): string => `哼，算你机灵，${fromLabel} 通过验证啦，欢迎杂鱼入群~♡`,
  verificationAdminOnly: "替人点「通过」是本群管理员的特权，杂鱼别乱点～",
  verificationAdminUnknown: "唔，本天才一时没查清你是不是管理员，别急，杂鱼稍后再点一次～",
  verificationOtherUser: "这不是你的验证按钮哦，杂鱼别乱点～",
  verificationMembershipUnknown: (label: string): string => `啧，本天才没能确认 ${label} 现在还在不在群里，所以这次没有贸然踢人；会继续重试，杂鱼管理员也检查下网络和本天才的成员查询权限！`,
  verificationChatKindUnknown: (label: string): string => `啧，本天才没能确认这个聊天是普通群还是超级群，所以这次没有拿 ${label} 乱试踢人接口；会继续重试，杂鱼管理员检查下网络！`,
  verificationFloodKickFailed: (label: string): string => `啧，${label} 没完成验证还在刷屏，本天才想把 TA 踢出去却没踢动……管理员快检查本天才的封禁权限！`,
  verificationTimeoutKickFailed: (label: string): string => `啧，${label} 超时没验证，本天才本想把 TA 踢出去，结果居然没踢动……肯定是哪个杂鱼管理员没给本天才封禁权限！快去检查，不然只能你们自己动手请 TA 出去咯♡`,
  verificationCleanupForbidden: (label: string, messageCount: number, missedCleanup: number): string => `啧，${label} 没通过验证，本天才把 TA 踢出去了，可本天才自己的 ${messageCount} 条验证消息里还有 ${missedCleanup} 条删不动……杂鱼管理员快看看本天才有没有删消息的权限♡`,
  verificationCleanupFailed: (label: string, missedCleanup: number): string => `啧，${label} 没通过验证，本天才把 TA 踢出去了，不过本天才自己的验证消息还有 ${missedCleanup} 条没清掉，多半是网络抽了一下♡`,
  verificationFloodKicked: (label: string): string => `啧，${label} 验证都没过就开始刷屏，本天才已经把 TA 踢出去啦♡`,
  verificationBotTimeout: (timeout: string, label: string): string => `啧，${timeout} 过去了都没有管理员愿意为机器人 ${label} 作保，本天才把这个来路不明的铁疙瘩踢出去啦♡`,
  verificationMemberTimeout: (label: string, timeout: string): string => `啧，${label} 磨磨蹭蹭 ${timeout} 都点不出验证按钮，本天才把 TA 踢出去啦，杂鱼动作太慢咯♡`,
  verificationBotReminder: (label: string, timeout: string, approveButton: string): string => `哦？谁把 ${label} 这个机器人拎进来的？铁疙瘩自己可点不了按钮——${timeout}内得有管理员帮它点「${approveButton}」作保，不然本天才就把这个来路不明的铁皮杂鱼扔出去哦♡`,
  verificationMemberReminder: (values: Readonly<{ label: string; timeout: string; selfButton: string; approveButton: string }>): string => `喂，${values.label}，新来的杂鱼给本天才听好了，${values.timeout}内点下面的「${values.selfButton}」证明你不是机器人（管理员也可以点「${values.approveButton}」直接放你进来），不然本天才就一脚把你踢出去哦♡`,
  verificationReplyReminder: (label: string, timeout: string, selfButton: string): string => `喂，${label}，话都说上了，${timeout}内把下面的「${selfButton}」点一下啊杂鱼。再装看不见的话，本天才可要直接把你请出去咯♡`,
};
